apiVersion: apps/v1
kind: Deployment
metadata:
  name: taghive-2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taghive-2
  template:
    metadata:
      labels:
        app: taghive-2
    spec:
      containers:
      - name: taghive-2
        image: Taghive-2
        env:
        - name: DB_HOST
          value: mysql-service
        ports:
        - containerPort: 5001
        volumeMounts:
        - mountPath: /app/data
          name: app-data
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
      volumes:
      - name: app-data
        emptyDir: {}

