apiVersion: apps/v1
kind: Deployment
metadata:
  name: taghive-1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taghive-1
  template:
    metadata:
      labels:
        app: taghive-1
    spec:
      containers:
      - name: taghive-1
        image: taghive-1:latest
        ports:
        - containerPort: 5000
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        volumeMounts:
        - name: app-data
          mountPath: /app/data
      volumes:
      - name: app-data
        emptyDir: {}

