version: '3'

output: prefixed

tasks:
  build:
    cmds:
      - docker build -t taghive-1:latest apps/app_a
      - docker build -t taghive-2:latest apps/app_b

  scan:
    cmds:
      - snyk container test taghive-1:latest
      - snyk container test taghive-2:latest

  k8s-deploy:
    deps: [build, scan]
    cmds:
      - kubectl apply -f deployments/taghive-1-deployment.yaml
      - kubectl apply -f deployments/taghive-2-deployment.yaml

