# Start from a Python 3.9 base image
FROM python:3.9

# Install sqlite3
RUN apt-get update && apt-get install -y sqlite3

# Set the working directory to /app
WORKDIR /app

# Copy the application code and requirements.txt to the container
COPY app_b.py schema.sql requirements.txt ./

# Install the required Python packages
RUN pip install -r requirements.txt

# Create the database schema and insert data
RUN sqlite3 database.db < schema.sql

# Expose port 5001 for the Flask web application
EXPOSE 5001

# Start the Flask web application
CMD ["python", "app_b.py"]

