# Start from a Python 3.9 base image
FROM python:3.9

# Set the working directory to /app
WORKDIR /app

# Copy the requirements file to the container
COPY requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code to the container
COPY . .

# Expose port 5000 for the Flask web application
EXPOSE 5000

# Start the Flask web application
CMD ["python", "app_a.py"]

